In [1]:
# Import libraries 
import numpy as np 
import pandas as pd 
# Import label encoder 
from sklearn.preprocessing import LabelEncoder
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import confusion_matrix
from sklearn.metrics import jaccard_score
from sklearn.metrics import classification_report

# Import dataset 
df = pd.read_csv('/Users/prathamtekriwal/Desktop/new pro/Flight-Delay-Prediction/Data/Processed_data45.csv')

In [2]:
df.head()

year  month  day carrier origin dest  delayed
0  2013      1    1      UA    EWR  IAH        0
1  2013      1    1      UA    LGA  IAH        0
2  2013      1    1      AA    JFK  MIA        0
3  2013      1    1      B6    JFK  BQN        0
4  2013      1    1      DL    LGA  ATL        0

In [3]:
columns= ['carrier','dest', 'origin']
le=LabelEncoder()
for i in columns:
     df[i]=le.fit_transform(df[i])

In [4]:
df['carrier'].unique()

array([11,  1,  3,  4,  5,  9, 12, 14, 13,  7,  2,  0,  6,  8, 15, 10])

In [5]:
df['origin'].unique()

array([0, 2, 1])

In [6]:
df['dest'].unique()

array([ 43,  57,  12,   4,  68,  35,  42,  53,  70,  99,  49,  89,  30,
        11,  48,  60,  32,  82,  91,  73,  16,  23,  14,  29,  94,  61,
        92, 103,  58,  88,  81,  98,  95,  79,  24,  47,  21,  55,  74,
        83,  28,  22,  96,  64,  46,  54,  40,  10,   5,  13,  72,  97,
        33,   6,  78,  45,  85,  19,  41,  51,  27,   2,   7,  56,  59,
        37,  26,  15,  80,  38,  36,  52,  69,  84,  87,  71,  90,  67,
        25,  65,  93, 102,  77,  31,  75, 100,   9,  66,  18,  39,  17,
        62,  34,  76,   1,   8,   0,  44,  63,  86,  50,  20, 101,   3])

In [7]:
X = df.iloc[:, 0:6].values # from column(years) to column(distance)
X[0:5]

array([[2013,    1,    1,   11,    0,   43],
       [2013,    1,    1,   11,    2,   43],
       [2013,    1,    1,    1,    1,   57],
       [2013,    1,    1,    3,    1,   12],
       [2013,    1,    1,    4,    2,    4]])

In [8]:
y = df['delayed']
y.head().to_frame()

delayed
0        0
1        0
2        0
3        0
4        0

In [9]:
for i in range(0, 20):
    X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=i)
    
    #creating Logistic Regression classifier
    clf = LogisticRegression(random_state=i)
    clf.fit(X_train, y_train)
    
    #determining the score
    train_score = clf.score(X_train, y_train)
    test_score = clf.score(X_test, y_test)
    print("Test: {}, Train: {} and Random State: {}".format(test_score, train_score, i))

Test: 0.8677409500534596, Train: 0.8716148100627779 and Random State: 0
Test: 0.8725217656942111, Train: 0.8704195878965617 and Random State: 1


/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/sklearn/linear_model/_logistic.py:469: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


Test: 0.8718649763250343, Train: 0.8705837877468726 and Random State: 2


/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/sklearn/linear_model/_logistic.py:469: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


Test: 0.8702306399877806, Train: 0.8709923780720646 and Random State: 3
Test: 0.8714372995265007, Train: 0.8706907085796332 and Random State: 4
Test: 0.8681533526806171, Train: 0.8715117078311873 and Random State: 5
Test: 0.8724453948373301, Train: 0.8704386809024118 and Random State: 6
Test: 0.8691461738200703, Train: 0.871263498755136 and Random State: 7


/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/sklearn/linear_model/_logistic.py:469: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


Test: 0.8700778982740186, Train: 0.8710305640837648 and Random State: 8
Test: 0.8694822055903467, Train: 0.8711794895293956 and Random State: 9
Test: 0.8710707194134718, Train: 0.8707823550077136 and Random State: 10
Test: 0.8700473499312662, Train: 0.8710382012861049 and Random State: 11
Test: 0.8712692836413625, Train: 0.8707327131925033 and Random State: 12
Test: 0.869879334046128, Train: 0.8710802058989751 and Random State: 13
Test: 0.870933251871086, Train: 0.8708167224182437 and Random State: 14
Test: 0.8728577974644876, Train: 0.8703355786708213 and Random State: 15


/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/sklearn/linear_model/_logistic.py:469: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


Test: 0.8712081869558577, Train: 0.8707479875971834 and Random State: 16
Test: 0.8718038796395295, Train: 0.8705990621515527 and Random State: 17


/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/sklearn/linear_model/_logistic.py:469: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


Test: 0.8699098823888805, Train: 0.8710725686966351 and Random State: 18
Test: 0.8714983962120055, Train: 0.8706754341749531 and Random State: 19


In [10]:
X_train, X_test, y_train, y_test = train_test_split( X, y, test_size=0.2, random_state=4)
print ('Train set:', X_train.shape,  y_train.shape)
print ('Test set:', X_test.shape,  y_test.shape)

Train set: (261876, 6) (261876,)
Test set: (65470, 6) (65470,)


In [11]:
LR = LogisticRegression(C=0.01, solver='liblinear').fit(X_train,y_train)
LR

LogisticRegression(C=0.01, solver='liblinear')

In [12]:
#Now we can predict using our test set:

In [13]:
yhat = LR.predict(X_test)
yhat

array([0, 0, 0, ..., 0, 0, 0])

In [14]:
yhat_prob = LR.predict_proba(X_test)
yhat_prob

array([[0.86655236, 0.13344764],
       [0.8624377 , 0.1375623 ],
       [0.89051981, 0.10948019],
       ...,
       [0.85742407, 0.14257593],
       [0.8697489 , 0.1302511 ],
       [0.87648719, 0.12351281]])

In [15]:
jaccard_score(y_test, yhat)

np.float64(0.0)

In [16]:
#confusion matrix :

In [17]:
confusion_matrix(yhat,y_test)

array([[57053,  8417],
       [    0,     0]])

In [18]:
print (classification_report(y_test, yhat))

              precision    recall  f1-score   support

           0       0.87      1.00      0.93     57053
           1       0.00      0.00      0.00      8417

    accuracy                           0.87     65470
   macro avg       0.44      0.50      0.47     65470
weighted avg       0.76      0.87      0.81     65470



/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/sklearn/metrics/_classification.py:1531: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/sklearn/metrics/_classification.py:1531: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/sklearn/metrics/_classification.py:1531: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  